import type { Metadata } from 'next';
import '@/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>{children}</body>
      <footer className="h-[30px] flex justify-center">
        <a href="https://growiary.com/" target="_black" rel="noopener noreferrer">
          <p className="text-xs text-gray-600 hover:text-blue-700">ⓒ Growiary</p>
        </a>
      </footer>
    </html>
  );
}
